
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = bomba
SERVER = centro

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = pdvsa.x

TARGETS_SVC.c = pdvsa_svc.c pdvsa_server.c pdvsa_xdr.c md5.c
TARGETS_CLNT.c = pdvsa_clnt.c pdvsa_client.c pdvsa_xdr.c md5.c
TARGETS = pdvsa.h pdvsa_xdr.c pdvsa_clnt.c pdvsa_svc.c pdvsa_client.c pdvsa_server.c md5.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g -DRPC_SVC_FG
LDLIBS += -g -lnsl -lpthread -lm
RPCGENFLAGS = -C

# Targets 

all : $(CLIENT) $(SERVER)

# $(TARGETS) : $(SOURCES.x) 
# 	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

