/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PDVSA_H_RPCGEN
#define _PDVSA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ticket {
	int numero;
	int ip_centro;
	int hora;
};
typedef struct ticket ticket;

struct reto {
	u_int *respuesta;
	int reto;
};
typedef struct reto reto;

#define PDVSA_PROG 0x30810272
#define PDVSA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PEDIR_TIEMPOS 1
extern  int * pedir_tiempos_1(int *, CLIENT *);
extern  int * pedir_tiempos_1_svc(int *, struct svc_req *);
#define PEDIR_GASOLINA 2
extern  int * pedir_gasolina_1(ticket *, CLIENT *);
extern  int * pedir_gasolina_1_svc(ticket *, struct svc_req *);
#define VALIDAR_RESPUESTA 3
extern  ticket * validar_respuesta_1(reto *, CLIENT *);
extern  ticket * validar_respuesta_1_svc(reto *, struct svc_req *);
extern int pdvsa_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PEDIR_TIEMPOS 1
extern  int * pedir_tiempos_1();
extern  int * pedir_tiempos_1_svc();
#define PEDIR_GASOLINA 2
extern  int * pedir_gasolina_1();
extern  int * pedir_gasolina_1_svc();
#define VALIDAR_RESPUESTA 3
extern  ticket * validar_respuesta_1();
extern  ticket * validar_respuesta_1_svc();
extern int pdvsa_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ticket (XDR *, ticket*);
extern  bool_t xdr_reto (XDR *, reto*);

#else /* K&R C */
extern bool_t xdr_ticket ();
extern bool_t xdr_reto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PDVSA_H_RPCGEN */
