/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pdvsa.h"
#include "centro.h"
#include "md5.h"


int cont =1;

int *
pedir_tiempos_1_svc(int *argp, struct svc_req *rqstp)
{
  static int  result;
  
  result = tiempo;
 
  
  return &result;
}

int *
pedir_gasolina_1_svc(ticket *argp, struct svc_req *rqstp){
  static int  result;
  struct ticket aux;
  aux = *argp;
  int r;
  
  if (tiempo_mon - aux.hora <= 10 && aux.ip_centro != 0 && aux.ip_centro == ip){
    if(inventario >= 38000){
      inventario -= 38000;

      fprintf(log_centro,"Evento en el tiempo %d:\n\t Se acepta el ticket:\n\t\t | TicketNo: %d || IP: 159.90.10.%d || Tiempo: %d |\n",tiempo_mon,aux.numero,aux.ip_centro,aux.hora);
      fprintf(log_centro,"Evento en el tiempo %d:\n\tEl cliente solicita gasolina y el centro puede responder la peticion\n",tiempo_mon);
      fprintf(log_centro,"\tInventario actual del centro: %d\n",inventario);

      result = -1;
    }  
    else{

      fprintf(log_centro,"Evento en el tiempo %d:\n\t Se acepta el ticket: \n\t\t | TicketNo: %d || IP: 159.90.10.%d || Tiempo: %d |\n",tiempo_mon,aux.numero,aux.ip_centro,aux.hora);
      fprintf(log_centro,"Evento en el tiempo %d:\n\tEl cliente solicita gasolina y el centro no puede responder la peticion\n",tiempo_mon);
      fprintf(log_centro,"\tInventario actual del centro: %d\n",inventario);

      result = -2;    
    }
  }  
  else{
    fprintf(log_centro,"Evento en el tiempo %d:\n\t Se rechaza un ticket invalido:\n\t\t  TicketNo: %d \n\t Se genera un nuevo reto para autenticar al cliente\n",tiempo_mon,aux.numero);
    int randNum;
    srand(time(NULL));
    randNum = rand () % (101) + 0; 
    fprintf(log_centro,"\tLa entrada del reto es: %d\n",randNum);
    result = randNum;
  }  
  return &result;
}

ticket *
validar_respuesta_1_svc(reto *argp, struct svc_req *rqstp)
{
  static ticket  result;
  char mensaje[80];
  char mensaje2[80];
  char mensaje3[80];
  sprintf( mensaje, "%d", argp->reto );
  unsigned *d = md5(mensaje, strlen(mensaje));
  sprintf( mensaje2, "%u", *(argp->respuesta) );
  sprintf( mensaje3, "%u", *d );
  fprintf(log_centro,"\tLa solucion al reto es: %s. La solucion del cliete es: %s\n",mensaje3,mensaje2);
  if(strcmp(mensaje3,mensaje2)==0){
    fprintf(log_centro,"\tSe acepta la solucion del cliente. El cliente ha superado el reto\n");
    result.numero = cont++;
    result.hora = tiempo_mon;
    char tmp[10];
    FILE *f = popen("/sbin/ifconfig eth0 | grep 'addr:' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f4", "r");
    fgets(tmp, sizeof(tmp), f);
    pclose(f);
    ip = atoi(tmp);
    result.ip_centro = ip;
    fprintf(log_centro,"\tSe emite el ticket: \n\t\t | TicketNo: %d || IP: 159.90.10.%d || Tiempo: %d |\n",result.numero,result.ip_centro,result.hora);
  }
  else {
    fprintf(log_centro,"\tNo se acepta la solucion del cliente.\n");
  }

  return &result;
}
